server:
  port: 7001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.93:3306/canal?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
  application:
    name: spring-canal
  jooq:
    sql-dialect: mysql
  flyway:
    baseline-on-migrate: true
canal:
  server: 192.168.1.93:11111
  destination: example